General:
  dry_run: false
  main_dir: flac
  max_workers: 8
  console_level: DEBUG
  file_level: DEBUG

Rymporter:
  collection: d.rp,albjh,tn,v,o,g,n9999999.html
  field_definitions:
    album_id: RYM_ALBUMID
    album_title: ALBUM
    artist_id: RYM_ALBUMARTISTID
    artist_name: ALBUMARTIST
    artist_collab: ALBUMARTISTCOLLAB
    date: DATE
    genre_id: RYM_GENREID
    genre_name: GENRE
    rating: RYM_RATING
    ownership: RYM_OWNERSHIP
    tag: RYM_TAG
    label_id: RYM_LABELID
    label_name: LABEL
    label_catalognr: CATALOGNR
  fields_to_modify:
    album_id: true
    album_title: false
    artist_id: true
    artist_name: false
    artist_collab: false
    date: false
    genre_id: true
    genre_name: true
    rating: true
    ownership: false
    tag: true
    label_id: false
    label_name: false
    label_catalognr: false

Rymfetcher:
  username: user21172121683

Flagger:
  skip_integrity_check: false
  problems_field: PROBLEMS
  timestamp: PROBLEMS_LASTCHECKED
  streamstamp: FLAC_STREAM
  cover_target_size: [1000, 1000]
  cover_square: True
  cover_allowed_formats:
    - jpeg
  tags_to_check:
    - GENRE
    - MUSICBRAINZ_ALBUMID
    - MUSICBRAINZ_ALBUMARTISTID
    - MUSICBRAINZ_ARTISTID
    - MUSICBRAINZ_TRACKID
    - LYRICS
    - RYM_ALBUMID
    - RYM_ALBUMARTISTID
    - ALBUMARTIST
    - ALBUM
    - DATE
    - REPLAYGAIN_ALBUM_GAIN
    - REPLAYGAIN_ALBUM_PEAK
    - REPLAYGAIN_TRACK_GAIN
    - REPLAYGAIN_TRACK_PEAK

Ogger:
  ogg_dir: ogg
  track_id_field: MUSICBRAINZ_RELEASETRACKID
  filename_match: true
  quality: 4
  sample_rate: 44100
  channels: 2
  fields_to_preserve:
    - ALBUM
    - ALBUMARTIST
    - ARTIST
    - DISCNUMBER
    - DISCTOTAL
    - GENRE
    - REPLAYGAIN_ALBUM_GAIN
    - REPLAYGAIN_ALBUM_PEAK
    - REPLAYGAIN_TRACK_GAIN
    - REPLAYGAIN_TRACK_PEAK
    - MUSICBRAINZ_ALBUMID
    - MUSICBRAINZ_ALBUMARTISTID
    - MUSICBRAINZ_ARTISTID
    - MUSICBRAINZ_RELEASEGROUPID
    - MUSICBRAINZ_RELEASETRACKID
    - MUSICBRAINZ_TRACKID
    - TITLE
    - TRACKNUMBER
    - TRACKTOTAL
    - DATE
    - LYRICS

ReBrainer:
  username: user21172121683
  field_map:
    ALBUM: release.release-group.title
    ALBUMARTIST: release.release-group.artist-credit.artist.name
    ALBUMARTISTSORT: release.release-group.artist-credit.artist.sort-name
    ARRANGER: X
    ARTIST: X
    ARTISTSORT: X
    ASIN: X
    BARCODE: X
    CATALOGNUMBER: X
    COMPILATION: X
    COMPOSER: X
    COMPOSERSORT: X
    CONDUCTOR: X
    DIRECTOR: X
    DISCNUMBER: X
    DISCSUBTITLE: X
    DISCTOTAL: X
    DJMIXER: X
    ENGINEER: X
    ISRC: X
    LABEL: release.label-info-list.label.name
    LANGUAGE: release.text-representation.language
    LYRICIST: X
    MEDIA: X
    MIXER: X
    MUSICBRAINZ_TRACKNUMBER: X
    ORIGINALDATE: release.release-group.first-release-date
    PERFORMER: X
    PRODUCER: X
    RELEASEALBUMTITLE: release.title
    RELEASECOMMENT: X
    RELEASECOUNTRY: release.country
    RELEASEDATE: release.date
    RELEASESTATUS: release.status
    RELEASETYPE: release.release-group.primary-type
    RELEASETYPESECONDARY: release.release-group.secondary-type-list
    REMIXER: X
    SCRIPT: release.text-representation.script
    SERIES: X
    TITLE: X
    TRACKNUMBER: X
    TRACKTOTAL: X
    WORK: X
    YEAR: X
  include:
    - artists
    - labels
    - recordings
    - release-groups
    - media
    - artist-credits
    - discids
    - isrcs
    - recording-level-rels
    - work-level-rels
    - annotation
    - aliases
    - tags
    - user-tags
    - area-rels
    - artist-rels
    - label-rels
    - place-rels
    - event-rels
    - recording-rels
    - release-rels
    - release-group-rels
    - series-rels
    - work-rels
    - instrument-rels

ReCoder:
  level: 8
  stamp: ENCODE_LEVEL

Stamper:
  stamps:
    COMMENT: no rights reserved
  map:
    LYRICS: UNSYNCEDLYRICS
  clear_source: true

Boxxxer:
  mixxx_db: mixxxdb.sqlite
  output: rekordbox.xml
  playlist_dir: m3u8
  first_cue_beat: true
  hot_to_memory: True
  bpm_tolerance: 0.1

Lister:
  filename: album
